### ISSUE TITLE
backup job did not expire on defined time

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#10]
I have a failed backupjob with retention of 1hour, created 27 hours ago:

```
$ kubectl -n backup-tenant-2 get backupjobs.ys.jibudata.com
NAME                                                    AGE
stone-backup-job-0f6bad0b-b2b7-4264-8b53-4c7fece85d71   27h  <===========

$ kubectl -n backup-tenant-2 get backupjobs.ys.jibudata.com stone-backup-job-0f6bad0b-b2b7-4264-8b53-4c7fece85d71 -o yaml
spec:
  action: StartJob
  backupName: stone-backup-plan-c3d984aa-5d84-4dee-9782-469231629545
  backupPlanRef:
    clusterName: "372731001564073046"
    copyMethod: filesystem
    namespaces:
    - test
    policy:
      retention: 1 <=========
  phase: JobFailed
status:
  report:
    endTime: "2021-09-17T08:49:24Z"
    expiredTime: "2021-09-17T09:49:24Z"
    startTime: "2021-09-17T08:49:24Z"
```

Why retention not work on failed job?
If it can not expire, the report.expiredTime should not be set.

**Comment by jerry-jibu** [comment]
fix is under test

**Comment by half-life666** [comment]
Fixed earlier, have you verified this case? @stoneshi-yunify

**Comment by stoneshi-yunify** [comment]
@half-life666

I just verified and found it isn't working as expected:

1. I created a backupplan and backupjob, set the retention to 1 hour. The job completed successfully. 1 hour later, the backupjob cr was deleted, but the data still exists in s3 storage.
```
  name: short-i5zc6
  namespace: backup-tenant-369641743475338021
  resourceVersion: "44479690"
  selfLink: /apis/ys.jibudata.com/v1alpha1/namespaces/backup-tenant-369641743475338021/backupjobs/short-i5zc6
  uid: 3bb2832d-db35-481f-af4f-0e8ff2f8ff99
spec:
  action: StartJob
  backupName: short
  tenant: "369641743475338021"
```

2. I created a incorrect backupplan and backupjob, set the retention to 1 hour. The job did not start (as expected), and it did not expire in 1hour. The job cr still exists.
```
root@i-k70jhesn:~# kubectl -n backup-tenant-369641743475338021 get backupjobs.ys.jibudata.com xx-i5zc6 -o yaml
apiVersion: ys.jibudata.com/v1alpha1
kind: BackupJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ys.jibudata.com/v1alpha1","kind":"BackupJob","metadata":{"annotations":{},"name":"xx-i5zc6","namespace":"backup-tenant-369641743475338021"},"spec":{"action":"StartJob","backupName":"xx","tenant":"369641743475338021"}}
  creationTimestamp: "2021-09-29T08:24:41Z"
  finalizers:
  - finalizer.backup.ys.jibudata.com
  generation: 1
  managedFields:
  - apiVersion: ys.jibudata.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:action: {}
        f:backupName: {}
        f:tenant: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-09-29T08:24:41Z"
  - apiVersion: ys.jibudata.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"finalizer.backup.ys.jibudata.com": {}
      f:status:
        .: {}
        f:conditions: {}
        f:phase: {}
        f:report:
          .: {}
          f:startTime: {}
    manager: manager
    operation: Update
    time: "2021-09-29T08:25:04Z"
  name: xx-i5zc6
  namespace: backup-tenant-369641743475338021
  resourceVersion: "44754558"
  selfLink: /apis/ys.jibudata.com/v1alpha1/namespaces/backup-tenant-369641743475338021/backupjobs/xx-i5zc6
  uid: cbef360e-e044-41f9-b28c-90a500118553
spec:
  action: StartJob
  backupName: xx
  tenant: "369641743475338021"
status:
  conditions:
  - lastHeartbeatTime: "2021-09-29T09:32:51Z"
    lastTransitionTime: "2021-09-29T08:24:56Z"
    message: completed to reconcile backup job
    reason: ReconcileCompleted
    status: "True"
    type: ReconcileComplete
  - lastHeartbeatTime: "2021-09-29T09:32:51Z"
    lastTransitionTime: "2021-09-29T08:24:56Z"
    message: completed to reconcile backup job
    reason: ReconcileCompleted
    status: "False"
    type: ReconcileProgressing
  - lastHeartbeatTime: "2021-09-29T09:32:51Z"
    lastTransitionTime: "2021-09-29T08:25:04Z"
    message: backup job not started yet
    reason: BackupJobNotStarted
    status: "False"
    type: BackupJobRunning
  - lastHeartbeatTime: "2021-09-29T09:32:51Z"
    lastTransitionTime: "2021-09-29T08:25:04Z"
    message: backup job not started yet
    reason: BackupJobNotStarted
    status: "False"
    type: BackupJobCompleted
  phase: Ready
  report:
    startTime: "2021-09-29T08:24:56Z"
root@i-k70jhesn:~# kubectl -n backup-tenant-369641743475338021 get backupplans.ys.jibudata.com xx -o yaml
apiVersion: ys.jibudata.com/v1alpha1
kind: BackupPlan
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ys.jibudata.com/v1alpha1","kind":"BackupPlan","metadata":{"annotations":{},"name":"xx","namespace":"backup-tenant-369641743475338021"},"spec":{"clusterName":"3737586399783599","copyMethod":"filesystem","excludePV":true,"excludedResources":["persistentvolumes","persistentvolumeclaims"],"namespaces":["test"],"policy":{"retention":1},"storageName":"374721143514393397","storageRef":{"desc":"A S3 compatible object store created by Kubesphere","displayName":"kkk","isDefaultStorage":true,"s3Config":{"accessKeyId":"a3ViZXNwaGVyZS1jbG91ZC0zNjk2NDE3NDM0NzUzMzgwMjEta3ViZXNwaGVyZS1jbG91ZC0zNjk2NDE3NDM0NzUzMzgwMjE=","bucket":"kubesphere-cloud-369641743475338021","credsSecretName":"374721143514393397-token","insecure":true,"region":"pek3b","s3url":"http://103.61.38.159:31774","secretAccessKey":"ds5O8AgHIINvdjSbDZcc2L9d5u8pOac3viZfB2fX"},"s3Provider":"aws","tenant":"369641743475338021","volumeSnapshotConfig":{}},"tenant":"369641743475338021"}}
  creationTimestamp: "2021-09-29T08:24:02Z"
  finalizers:
  - finalizer.backup.ys.jibudata.com
  generation: 1
  managedFields:
  - apiVersion: ys.jibudata.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:clusterName: {}
        f:copyMethod: {}
        f:excludePV: {}
        f:excludedResources: {}
        f:namespaces: {}
        f:policy:
          .: {}
          f:retention: {}
        f:storageName: {}
        f:storageRef:
          .: {}
          f:desc: {}
          f:displayName: {}
          f:isDefaultStorage: {}
          f:s3Config:
            .: {}
            f:accessKeyId: {}
            f:bucket: {}
            f:credsSecretName: {}
            f:insecure: {}
            f:region: {}
            f:s3url: {}
            f:secretAccessKey: {}
          f:s3Provider: {}
          f:tenant: {}
          f:volumeSnapshotConfig: {}
        f:tenant: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-09-29T08:24:02Z"
  - apiVersion: ys.jibudata.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"finalizer.backup.ys.jibudata.com": {}
      f:status:
        .: {}
        f:conditions: {}
        f:currentJobName: {}
        f:currentJobPhase: {}
        f:phase: {}
    manager: manager
    operation: Update
    time: "2021-09-29T08:25:04Z"
  name: xx
  namespace: backup-tenant-369641743475338021
  resourceVersion: "44756849"
  selfLink: /apis/ys.jibudata.com/v1alpha1/namespaces/backup-tenant-369641743475338021/backupplans/xx
  uid: 62c68ca3-5fc8-467f-9b08-e4ab06d6bc74
spec:
  clusterName: "3737586399783599"
  copyMethod: filesystem
  excludePV: true
  excludedResources:
  - persistentvolumes
  - persistentvolumeclaims
  namespaces:
  - test
  policy:
    retention: 1
  storageName: "374721143514393397"
  storageRef:
    desc: A S3 compatible object store created by Kubesphere
    displayName: kkk
    isDefaultStorage: true
    s3Config:
      accessKeyId: a3ViZXNwaGVyZS1jbG91ZC0zNjk2NDE3NDM0NzUzMzgwMjEta3ViZXNwaGVyZS1jbG91ZC0zNjk2NDE3NDM0NzUzMzgwMjE=
      bucket: kubesphere-cloud-369641743475338021
      credsSecretName: 374721143514393397-token
      insecure: true
      region: pek3b
      s3url: http://103.61.38.159:31774
      secretAccessKey: 
    s3Provider: aws
    tenant: "369641743475338021"
    volumeSnapshotConfig: {}
  tenant: "369641743475338021"
status:
  conditions:
  - lastHeartbeatTime: "2021-09-29T09:33:27Z"
    lastTransitionTime: "2021-09-29T08:24:30Z"
    message: failed to reconcile backup plan
    reason: ReconcileFailed
    status: "False"
    type: ReconcileComplete
  - lastHeartbeatTime: "2021-09-29T09:33:27Z"
    lastTransitionTime: "2021-09-29T08:24:30Z"
    message: failed to reconcile backup plan
    reason: ReconcileFailed
    status: "False"
    type: ReconcileProgressing
  - lastHeartbeatTime: "2021-09-29T09:33:27Z"
    lastTransitionTime: "2021-09-29T08:24:30Z"
    message: start to initialize the backup plan
    reason: InitStatus
    status: Unknown
    type: BackupPlanAvailable
  currentJobName: xx-i5zc6
  currentJobPhase: Ready
  phase: Error
```

**Comment by stoneshi-yunify** [comment]
![image](https://user-images.githubusercontent.com/70880165/135245045-1dc9e649-6ada-43d0-87aa-34f2438a0cb3.png)

for case 1, data still exists in s3 storage

**Comment by half-life666** [comment]
For case 1, the data is deleted by velero background process, which may trigger not in time. You can log into the cluster and look at corresponding velero `Backup` CR, to see if the CR still exists.

For case 2, since the job did not start, so the retention does not work. The retention works only when the job started.

**Comment by jerry-jibu** [comment]
@stoneshi-yunify  can this issue be closed based on explanation ? thanks.
